parser:
  goroutines-amount: 5
  default-interval: 15s
  load-data-interval: 30s

database:
  host: database
  port: 5432
  database: postgres
  username: postgres
  password: '{{env "POSTGRES_PASSWORD"}}'

server:
  port: 8001

authorize:
  file-location: .admins.json