parser:
  goroutines-amount: 5
  default-interval: 10s

database:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: '{{env "POSTGRES_PASSWORD"}}'

server:
  host: localhost
  port: 8001